### PR TITLE
Fix crash and update for Swift 4

### PR DESCRIPTION
**Pull request by alexanderkhitev**

### CODE REVIEW

**Comment by phoney** [comment]
+1 

This looks like a good way to fix the problems on iOS 11.

**Review by perilsoul — APPROVED** [review]

**Review by nickseidel — APPROVED** [review]

**Comment by fbonilla** [comment]
How come this PR has never been merged?

**Comment by AndriyGo** [comment]
@alexanderkhitev maybe we should move this to some separate fork? Looks like this repo is not updated...

**Comment by phoney** [comment]
I use
    pod 'DGRunkeeperSwitch', :git => 'https://github.com/alexanderkhitev/DGRunkeeperSwitch.git', :branch => 'master'

**Comment by fbonilla** [comment]
I've decided to use another project with more activity. https://github.com/gmarm/BetterSegmentedControl

**Comment by alexanderkhitev** [comment]
@AndriyGo sorry for late response I was on holiday. I do not mind if someone does that, an active fork from my fork, because I currently do not have time to support the open source framework and accept or view pull requests.

**Comment by phoney** [comment]
@AndriyGo Your commits break this branch for me. The first part of this PR updated to swift 4 and fixed some compile errors in the 1.1.4 version. You've updated to swift 4.2 without any kind of versioning or tag. My project hasn't updated to swift 4.2 so I can't consume your commits. The only way I can still use this branch is specifying the commit. That's not how this is supposed to work.

pod 'DGRunkeeperSwitch', :git => 'https://github.com/alexanderkhitev/DGRunkeeperSwitch.git', :commit => '2916ed50f8c57efc5f9b31867f41f9a670abe76a'

**Pull request closed without merging**
